apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website
spec:
  type: NodePort
  selector:
    app: website
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
